version: '3'
services:
 node:
   build: .
   tty: true
   restart: always
   command: yarn start
   ports:
     - '3002:3000'
   volumes:
    #  - .:/workspace:delegated
    #  - /workspace/node_modules
     - data:/workspace:delegated
    #  - node_modules:/workspace/node_modules
volumes:
  data:
  # node_modules: